* Wed Mar 24 2021 Cornelius Kölbel <cornelius.koelbel@netknights.it 3.5.2
- Update version number

* Thu Jan 28 2021 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.5.1
- Update version number

* Tue Dec 22 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.5
- Update version number

* Fri Oct 07 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.4.1dev3
- Update version number

* Fri Sep 11 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.4
- Update version number

* Tue May 19 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.3.3
- Update version number

* Wed May 06 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.3.2
- Update version number

* Wed Apr 29 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.3.1
- Update version number

* Sun Apr 05 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.3
- Update version number

* Fri Jan 17 2020 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.2.2
- Update version number

* Tue Dec 31 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.2.1-1
- Update version number

* Mon Dec 02 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.2
- Add Barracuda MySQL fix to NGinX installation
- Do not restart MySQL database, if Barracuda fix is already in place

* Fri Nov 15 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.1.2
- Update version number

* Wed Oct 02 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.1.1-2
- Fix the NGINX installation

* Wed Sep 25 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.1.1-1
- Update version number

* Wed Sep 04 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.1
- Update version number  

* Mon Jun 17 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.0.2-2
- Fix update mechansim

* Mon Jun 17 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.0.2-1
- Remove links before recreating them

* Thu May 23 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.0.1
- Run with privacyIDEA 3.0.1

* Thu Nov 16 2017 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.20.1-2
- Fix upgrade: Do not revert changes in pi.cfg

* Thu Feb 11 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.10
- packaging of release 2.10

* Tue Jan 26 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.10dev5-1
- initial RPM packaging
