* Thu May 23 2019 Cornelius Kölbel <cornelius.koelbel@netknights.it> 3.1
- Add timing to log file
- return RLM_MODULE_NOTFOUND in case the user is not found
- remove static user-dir mapping

* Tue Oct 11 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.15
- Add User Attribute Mapping

* Wed Apr 13 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.11-1
- Adding radius config

* Thu Feb 11 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.10
- packaging of release 2.10

* Thu Jan 27 2016 Cornelius Kölbel <cornelius.koelbel@netknights.it> 2.10dev5-1
- initial RPM packaging

